var a;  console.log(typeof a);
var s = '1s'; console.log(s++);
console.log(!!"false");
console.log(!!undefined);
console.log(typeof -Infinity);
console.log(10 % "1");
console.log(undefined == null);
console.log(false === "");
console.log(typeof "2E+2");
a=3e+3;a++;
console.log(a);